source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


# gem 'carrierwave'
#gem 'rmagick'


gem "bcrypt-ruby", :require => "bcrypt"
 gem 'annotate', '2.5.0'
 gem 'factory_girl_rails', '4.1.0'

#gem 'carrierwave'
#gem 'rmagick'



# Gems used only for assets and not required
# in production environments by default.


gem 'sass-rails',   '~> 3.2.3'
gem 'coffee-rails', '~> 3.2.1'

  gem 'sass-rails',   '~> 3.2.3'

gem 'jquery-rails'
gem 'bootstrap-sass'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby


# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', :platforms => :ruby
gem 'uglifier', '>= 1.0.3'
gem 'jquery-rails'
gem 'ransack'
gem 'bcrypt-ruby'

gem 'best_in_place'
gem 'omniauth-facebook'

group :test, :development do
  gem "rspec-rails", "~> 2.0"
end

gem "bootstrap-sass"

group :test do
  gem 'faker'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'launchy'
end
