source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'mail', '~> 2.5.3'


#gem 'best_in_place'
gem 'bootstrap-sass'
gem 'rspec-rails'
gem 'devise'
gem 'client_side_validations'

# group :test, :development do
#   gem "rspec-rails", "~> 2.0"
# end
gem 'gmaps4rails'
#gem 'simplecov'
gem 'carrierwave'
#gem 'rmagick'
gem 'bootstrap-datepicker-rails'

gem "bcrypt-ruby", :require => "bcrypt"
 #gem 'annotate', '2.5.0'


gem 'factory_girl_rails', '4.1.0'

#gem 'omniauth-facebook'

# Gems used only for assets and not required
# in production environments by default.

gem 'ancestry'
gem 'coffee-rails', '~> 3.2.1'
gem 'sass-rails',   '~> 3.2.3'
gem 'jquery-rails'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby


# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', :platforms => :ruby
gem 'uglifier', '>= 1.0.3'
gem 'ransack'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

group :test, :development do
end

group :test do
  gem 'faker'
  gem 'guard-rspec'
end
#group :test do
 # gem 'faker'
  #gem 'capybara'
  #gem 'guard-rspec'
  #gem 'launchy'
#end
